# -*- coding: utf-8 -*-
"""data-analysis-foundations-project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qDAuWdWySQtmxt9fwRgRzyyJf8woBBhk
"""

#Importando as bibliotecas necessári
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

#Importanto o dataset
df = pd.read_csv('dados_venda_empresa1.csv')

#Exibindo as primeiras linhas para inspeção inicial
print(df.head())

#Exibindo o shape do Dataset (Qtd de Linhas e Colunas)
print(f"Seu dataset tem {df.shape[0]} linha e {df.shape[1]} colunas")

#Exibindo as Colunas do Dataset
print(df.columns)

#Exibindo as Colunas do Dataset em Lista
print(df.columns.tolist())

#Exibindo a quantidade de dados faltantes (nulos) em cada coluna
dados_faltantes = df.isnull().sum()
print(dados_faltantes)

#Calcula estatísticas descritivas (média, desvio padrão, etc.) do Dataset
print(df.describe())

#Exibe a quantidade de valores iguais a 0 nas 3 colunas quantidade, preço_unitário e total_venda
df[['quantidade','preco_unitario','total_venda']].eq(0).sum()

#Somando os valores da coluna total_venda
print(df['total_venda'].sum())

#Multiplicando os valores da coluna quantidade pela coluna preco_unitario e preenchendo na coluna total_venda
df['total_venda'] = df['quantidade'] * df['preco_unitario']
print(df['total_venda'])

#Exibe a média dos valores da coluna quantidade
print(df['quantidade'].mean())

#Filtra itens da categoria Eletrônicos
print(df[df['categoria'] == 'Eletrônicos'])

#Filtra itens da categoria Eletrônicos com quantidade maior que 3
print(df[(df['categoria'] == 'Eletrônicos') & (df['quantidade'] > 3 )])

#Exibe a media de quantidade vendida por categoria
print(df.groupby('categoria')['quantidade'].mean())

#Exibe a soma da quantidade vendida por categoria
print(df.groupby('categoria')['quantidade'].sum())

#Realiza múltiplas estatisticas por categorias (Média, soma, valor máximo e valor mínimo da quantidade de itens por categoria)
print(df.groupby('categoria')['quantidade'].agg(['mean','sum','max','min']))

#Corrige e converte a coluna preço_unitario, garantindo que é string, removendo ponto dos milhares e trocando virgula decimal por ponto
df['preco_unitario'] = df['preco_unitario'].astype(str).str.replace('.', '').str.replace(',', '.')

#converte para float
df['preco_unitario'] = pd.to_numeric(df['preco_unitario'], errors ="coerce")

#converte quantidade, se necessário
df['quantidade'] = pd.to_numeric(df['quantidade'], errors ="coerce")

#Multiplica os valores da coluna quantidade pela coluna preco_unitario e preenche na coluna total_venda
df['total_venda'] = df['quantidade'] * df['preco_unitario']

#Verificar tipo final da coluna preco_unitario
print(df['preco_unitario'].dtype)

"""Gráficos"""

#Plot de um gráfico simples de barras
df['categoria'].value_counts().plot(kind='bar')
plt.show()

#Plot de um histograma de distribuição dos valores de venda 'total_venda'
plt.figure(figsize=(8,6))
df['total_venda'].hist(bins=20)
plt.title('Distribuição dos Valores de Venda')
plt.xlabel('Valor de Venda')
plt.ylabel('Frequência')
plt.show()

#Distribuição de frequência por categoria (Horizontal Bar)
df['categoria'].value_counts().plot(kind='barh')
plt.show()

#Gráfico de pizza mostrando a distribuição de frequência por categoria
df['categoria'].value_counts().plot(kind='pie')
plt.show()

#Plot de gráfico de area com contagem de valores por categoria
df['categoria'].value_counts().plot(kind='area')
plt.show()

#Cria uma nova coluna STATUS_CLIENTE
df['STATUS_CLIENTE'] = np.where(df['total_venda'] > 10000, 'VIP', 'NAO VIP')

#Checa o head do data set
print(df.head())

#Garante que as informaçoes de data estao no formato datetime
df['data_venda'] = pd.to_datetime(df['data_venda'])

#Extrair as informações de uma coluna de data para quatro colunas (Ano, mês, dia e dia da semana)
df['ano'] = df['data_venda'].dt.year
df['mes'] = df['data_venda'].dt.month
df['dia'] = df['data_venda'].dt.day
df['dia_da_semana'] = df['data_venda'].dt.dayofweek

#Analisa a seguinte oportunidade: qual o total de vendas?
print(df['total_venda'].sum())

#Analisa a seguinte oportunidade: qual a media de vendas?
print(df['total_venda'].mean())

#Analisa a seguinte oportunidade: qual categoria vende mais?
print(df.groupby('categoria')['total_venda'].sum())

#Análisa a seguinte oportunidade: qual a maior venda individual?
print(df['total_venda'].max())

#Análisa a seguinte oportunidade: qual dia da semana há maior venda?
print(df.groupby('dia_da_semana')['total_venda'].sum())

"""Analise final"""

#Plot do gráfico de vendas totais por mês (1 a 12)
df.groupby('mes')['total_venda'].sum().plot(kind='bar')
plt.show()

#Plot de grafico de pizza do percentual de vendas por categoria
df['categoria'].value_counts(normalize=True).plot(kind='pie')
plt.show()

#Plot do grafico de vendas medias por dia da semana (0 a 6)
df.groupby('dia_da_semana')['total_venda'].mean().plot(kind='bar')
plt.show()

#Plot de um grafico de dispersao do dia da semana com o total de venda
df.plot(kind='scatter', x='dia_da_semana', y='total_venda')
plt.show()

#Plot do boxplot da distribuição de vendas por dia
df.boxplot(column='total_venda', by='dia_da_semana')
plt.show()

#Plot do boxplot por total de vendas por categoria
df.boxplot(column='total_venda', by='categoria')
plt.show()

#Plot do boxplot por total de vendas por mes
df.boxplot(column='total_venda', by='mes')
plt.show()

#Compara o valor medio de vendas entre vip e nao vip
print(df.groupby('STATUS_CLIENTE')['total_venda'].mean())

#Compara o valor total vendido entre vip e nao vip
print(df.groupby('STATUS_CLIENTE')['total_venda'].sum())

#Compara as compras dos vips e nao vips por categoria
print(df.groupby(['STATUS_CLIENTE', 'categoria'])['total_venda'].sum())

#Gera um gráfico de pizza comparando o total de vendas de vips e nao vips
df.groupby('STATUS_CLIENTE')['total_venda'].sum().plot(kind='pie')
plt.show()

#Gera um grafico de barras comparando as compras dos vips e nao vips por categoria
df.groupby(['STATUS_CLIENTE', 'categoria'])['total_venda'].sum().unstack().plot(kind='bar')
plt.show()